### ISSUE TITLE
set: user can change the location of taskfiles

### ISSUE THREAD

**Issue by chao1995** [cs2103jan2015-t09-4j/main#20]
so that I can have portability in using the application on various computers.

**Comment by NicholasN3Y** [comment]
export two files*  completedTasks.txt and toDoTasks.txt

**Comment by NicholasN3Y** [comment]
For v0.1 the files are present, in the default folder.
v0.2 will allow user to designate where the folders can be saved to.

**Comment by NicholasN3Y** [comment]
done set a new location as a default location
