### ISSUE TITLE
parser: fixed bugs as in comments

### ISSUE THREAD

**Issue by Muzamir** [cs2103jan2015-t09-4j/main#73]
bugs found:

add ... from 4pm to 6pm tomorrow
add finish tutorial 9 to page 23 (on bst) by this Friday  (on This Thursday)
    pay attention to regression: add ... on this Thursday this Thursday

**Comment by Muzamir** [comment]
There were a few bugs discovered Hence, test cases were created to tackle each bug. Refer to ParserTest.java for more

**Comment by chao1995** [comment]
fixed
